import "./globals.css";
import { Commissioner } from "next/font/google";

const commissioner = Commissioner({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  adjustFontFallback: true,
});

export const metadata = {
  title: "Bamboo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={commissioner.className}>{children}</body>
    </html>
  );
}
